language: android

branches:
  only:
  - master

env:
  global:
  - secure: C4HZgAfw2OotVXlTlflsVO8UlSDDxmUJ9famIlXWj2PYfsyo6zeOoYh2LNigt1HID6VYgNbjsaOrahWnzQ/CEyZMiHC4a2FXTzaGshhaze3U2m7Nk8ITKoSCdswv1xOF0CjVmPxuhk4x4ImUP+A90xpIu92HV3T0ePbCeRXRR0lcL4XEk05Dv44K5FWazyim7H5VtlpUtTHtMrSvOdQsmIQR1A+iAWLVjhRixNqmXcQDdq7nn1fg0stvp+4+EeHEOrEI5BQbI/fbJbO+ZngVdqv8C2NoTXhcxMw46tl7lP1mnWKGUukddhTH/Jr5Wt6KK8P6/bq+UXcNbz/qXKeh4p+d7OCgxinR6d8H2vms2k77v7I+YWrW+LNsxpCKvWZvTp7/kzjzwLuvD1J4E4GkMD0cukFR7Xv2mgdohrDCnssshTn1vXNGx7N6Ik3dpk9cPI0QAbrvLlF57iv0pxH9fM7TEsLONDRbj6ti1t+kro+w2w+punTTRbfbIDYG0PtypTnR0EELV7qU13dUpFQM4obcfebMA+vGFtHya8XiPEwT16alBZnjkDTDPo/Zt9o5PijW16MhSaAI3AtgqXYEMw5PtBUZ5LFhX0fMvvdr1YZZc8pKDKp47sffNGEYZmLDGd1EhCMcOrd3HZ/Nf7JU3D+pBzXvQ+0UstbQSfdRYlo=
  - secure: iG/IKvcyQA6iaquaPmq7RHNHi9JKT0aXiKnfdDNArPqjk5K4U+ywupybqokG5smvbDAcCS6PgV1Sy+xNGrSU1nklP8PWfAo+WDR+b9dEkt9A3xqTgXtuSwOlARuBBTie50IXW24yegQiPRFGI1GtyRyqt3f++cyXPeR8MzROyA7QqTZBVd7xniNaNtutDIpH0c63Zzf+MPApvwifPVW8wjV9lEiSLAI5RDbUAwPCpo9r5nWIo7U1FbBC2VAFFc7fICe97C/JOGpiiBH1TxcdgocshtH6YlUYIQca2RJ3KbamMrEUrhCYj2AtHFpgM7H5q10+i/rNYteaEv09ggNkcXdrOavQl5XFumcoDDKXKZ2JCqSXuZqXR7wuLxkZkbELsPjkyJ36X040E4wblfr8Na0PBe3tDfqt2h6IM1H4l+pzeTckP69D2zt80bnOYexN+MFLFk2HSCDAC/8nyXyNw9SunRNp+IUwjzd3YrP2fD9uCxLCHVuK4Jmvlbvd7PJTILUGEcKR7R+hQSSkIf64wpFNQnehUVYWcoGZpGdCLcT8Oy5rNZp6GgzF+UJcMkEsAnsOW6dW1lSaHff3XTXOYW4CpX8i5vMyyekhrLsIEft6uLMApDndw7RmFZLTtjH99Kwjkq+/RVbh+7Jy4V37yWkBwrkJ4mgBzZ0gbymHt6A=

android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - platform-tools
  - tools

  # The BuildTools version used by your project
  - build-tools-23.0.3

  # The SDK version used to compile your project
  - android-23

  # Additional components
  #- extra-google-google_play_services
  #- extra-google-m2repository
  - extra-android-m2repository
  #- addon-google_apis-google-19

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  # - sys-img-armeabi-v7a-android-19
  # - sys-img-x86-android-17

script:
- ./gradlew bintrayUpload
