branches:
  only:
  - master

env:
  matrix:
  - secure: pFjWvQ6GyDU3c4EXUcQY+XqyvGGQGQoXeRJhXBDA6IX/MwkY7XD7jb8HSDp6+EOuYDZ0qWRLNnHjwd9qjzCgzuD/fT+SuUWMqgfczErdRqNvVRCQoHlI2kWPoNKbspJDoirLJNMZcVvSkBe8DH5hu7xN02PaRqUTE350TZovFr2sjvOl+T2ZdJbDalM7Yh/vR7mHcgjnurAxHPgW+gznfVtdAJhWS316QD/t9OlSwbUenc0E7oR79QBpK4MsoK/Se6IG5MwWBJyguYwBWPQyGLCf3H9JZb0SrYYe2363fdA/P+yH3LprhTSRUoact83Rajc3mldaP759QkmZYPEzxpWUdj4NL4mmV5pgc0UKOwqV00sCPb0BuDk29nxUPBZFuWYVKGmIKbKBDYLbp92KW456Ra+2qaUr/Lh2R4vDcFOH691CjU2V/sfdfFIrkC/8BpDvxGwWGk3Z2E9ahLlEY+BIeXqv+y/5P8FW+mUGVOsQwObkrKTSg21Hwk7uK1Hv37glcxuWkSNJM7WS5b4thcTdvTcl7Smrps+KeuWeW84S/Zjh+eF3s8EBiwqltuXAWrxeRwRgNTVf/EiByMjJ2v7SRieONDMkpCo6/O0sgFrrPTgnNF3y2S+WqhiZreL5CcPB9pyLAih/smM0CtU2C658Yh6iyHeLT9YED6nrR+A=

language: android
android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - platform-tools
  - tools

  # The BuildTools version used by your project
  - build-tools-23.0.3

  # The SDK version used to compile your project
  - android-23

  # Additional components
  #- extra-google-google_play_services
  #- extra-google-m2repository
  - extra-android-m2repository
  #- addon-google_apis-google-19

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  # - sys-img-armeabi-v7a-android-19
  # - sys-img-x86-android-17

script:
- "./gradlew bintrayUpload -Pbintray.user=$bintray.user -Pbintray.apikey$bintray.apikey"
